twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        app_name: 'Application Name'
    date:
        format: d-m-Y H:i
        interval_format: '%%d days'
        timezone: Europe/Belgrade
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
