---
deployment:
 tasks:
 - export DEPLOYPATH=/home/glutenfr/data.ivanstanojevic.me
 - composer install
 - /bin/cp -R ./bin $DEPLOYPATH
 - /bin/cp -R ./config $DEPLOYPATH
 - /bin/cp -R ./src $DEPLOYPATH
 - /bin/cp -R ./templates $DEPLOYPATH
 - /bin/cp -R ./vendor $DEPLOYPATH
 - /bin/cp -R ./.htaccess $DEPLOYPATH
 - /bin/cp -R ./.index.php $DEPLOYPATH
