_email_recovery:
  path:         /_email/recovery
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: email/recovery.html.twig

_email_invite:
  path:         /_email/invite
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: email/invite.html.twig

_email_verify:
  path:         /_email/verify
  controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: email/verify.html.twig
