tle:
  name: "NORAD TLE"
  description: "Two line element set - orbital perturbation data sets published by North American Aerospace Defense
    Command and periodically refined so as to maintain a reasonable prediction capability on all space objects."
  path:
    route: "app_api_docs"
    params:
      name: "tle"
metar:
  name: "METAR"
  description: "Meteorological Terminal Air Report METAR - Aviation weather report updated every 15 minutes currently
    available for limited number of airports."
  path:
    route: "app_api_docs"
    params:
      name: "metar"
apollo:
  name: "Apollo JSON"
  description: "Data repository contains JSON documents of data from NASA Apollo missions. Data ranges from orbital parameters to food and medicine carried to each mission. Every dataset is obtained from Apollo By Numbers and structured in JSON format."
  path: "https://github.com/ivanstan/apollo-data/"
