parameters:
  locale: 'en'
  mail_from: 'no-replay@domain.com'
  default_timezone: 'Europe/Belgrade'
  date_format: 'd-m-Y H:i'
  app_name: 'Application Name'
  primary_color: '007bff'
  avatar_background: 'fff'
